52 set up database connection and the server
CA-G12/jack-trades pull request #53
Opened 2022-10-13 18:52 UTC by SaraDahman

2022-10-14 11:10 UTC, MohammedOmar123 approved these changes

2022-10-14 17:25 UTC, hkmusameh01 approved these changes

2022-10-15 16:47 UTC, Mu7ammadAbed requested changes

2022-10-15 16:47 UTC, Mu7ammadAbed commented on server/index.ts
> +      console.log(error);
```suggestion
      await sequelize.sync()
      app.listen(port, () => console.log(`Server is running on http://localhost:${ port }`))
    } catch (error) {        
      console.log('Error on synchronizing Database: ', error)
```

2022-10-15 16:47 UTC, Mu7ammadAbed commented on server/database/connection.ts
> +export const sequelize = new Sequelize(url, { dialectOptions: {ssl} });
```suggestion
const sequelize = new Sequelize(url, { dialect: 'postgres', dialectOptions: {ssl} });
export default sequelize;
```

2022-10-15 16:47 UTC, Mu7ammadAbed commented on server/app.ts
> + app.use('*', (req, res) => {
```suggestion
 app.get('*', (req, res) => {
```

2022-10-15 16:47 UTC, Mu7ammadAbed commented on server/app.ts
> +import cors from 'cors'
```suggestion
```

2022-10-15 21:57 UTC, MohammedOmar123 approved these changes
LGTM

2022-10-16 07:01 UTC, MohammedOmar123 approved these changes
LGTM

2022-10-16 07:02 UTC, Mu7ammadAbed approved these changes

2022-10-16 07:02 UTC, merged